fix type mismatch error for arm
damb/mseed pull request #8
Opened 2023-08-23 17:22 UTC by BIBIN-EUGINE

**Description**

Resolved the portable issues of mseed crate for arm target

**Testing**

Tested this changes with cross compliation for arm target and it complied successfully.

2023-08-23 17:34 UTC, BIBIN-EUGINE commented
Hi @damb , This PR is ready for review. Thanks

2023-08-23 19:36 UTC, damb commented
Great. Could you please fix the formatting, firstly. `cargo-fmt` is your friend. Thanks.

2023-08-24 13:03 UTC, damb requested changes
Thanks a lot.

Could you fix the requested changes, please? Also, could you have a look at the examples in the examples directory since they might require additional changes?

In addition, do you have experience with ARM based test runners for GitHub actions? It would be nice to have tests being executed on ARM, too.

2023-08-24 13:03 UTC, damb commented on src/io.rs
> +                (encoding as c_char).try_into().unwrap(),
Casting and converting (i.e. basically casting twice) is not required. Instead, use

```rust
encoding as _
```

and let the compiler infer the destination type (see https://doc.rust-lang.org/std/keyword.as.html).

2023-08-24 13:03 UTC, damb commented on src/pack.rs
> +            (info.encoding as c_char).try_into().unwrap(),
See above.

```rust
info.encoding as _
```

is the way to go.

2023-08-24 13:03 UTC, damb commented on src/pack.rs
> +        (*msr).encoding = (info.encoding as c_char).try_into().unwrap();
See above. Casting twice not required.

2023-08-24 13:03 UTC, damb commented on src/record.rs
> +            (buf.len() as c_ulong).into(),
See above. Casting twice is not required.

2023-08-24 13:03 UTC, damb commented on src/pack.rs
> +    let cnt_samples: c_long = 0;
See https://github.com/damb/mseed/pull/8#discussion_r1304279687.

2023-08-24 13:03 UTC, damb commented on src/pack.rs
> +    let cnt_samples: c_long = 0;
See https://github.com/damb/mseed/pull/8#discussion_r1304279687.

2023-08-24 13:03 UTC, damb commented on src/record.rs
> +        unsafe { check(raw::msr3_unpack_data(self.0, 0).try_into().unwrap()) }
The code should do what it is expected to do. Though, I prefer the shorter

```rust
unsafe { check(raw::msr3_unpack_data(self.0, 0)) as _ } 
```

since it is less verbose and IMO more idiomatic.

2023-08-24 13:03 UTC, damb commented on src/record.rs
> +        util::nstime_to_time(self.ptr().starttime.try_into().unwrap())
See above. Cast with `as _` instead.

2023-08-24 13:03 UTC, damb commented on src/record.rs
> +        unsafe { util::nstime_to_time(check_nst(raw::msr3_endtime(self.0).try_into().unwrap())?) }
Cast with `as _`.

2023-08-24 13:03 UTC, damb commented on src/record.rs
> +        self.ptr().samplecnt.try_into().unwrap()
Cast with `as _`.

2023-08-24 13:03 UTC, damb commented on src/record.rs
> +        self.ptr().numsamples.try_into().unwrap()
Cast with `as _`.

2023-08-24 13:03 UTC, damb commented on src/record.rs
> +                v.starttime.try_into().unwrap(),
Cast with `as _`.

2023-08-24 13:03 UTC, damb commented on src/record.rs
> +                start_time.try_into().unwrap(),
Cast with `as _`.

2023-08-24 13:03 UTC, damb commented on src/trace.rs
> +        util::nstime_to_time(self.ptr().earliest.try_into().unwrap())
Cast with `as _`.

2023-08-24 13:03 UTC, damb commented on src/trace.rs
> +        util::nstime_to_time(self.ptr().latest.try_into().unwrap())
Cast with `as _`.

2023-08-24 13:03 UTC, damb commented on src/trace.rs
> +        util::nstime_to_time(self.ptr().starttime.try_into().unwrap())
Cast with `as _`.

2023-08-24 13:03 UTC, damb commented on src/trace.rs
> +        util::nstime_to_time(self.ptr().endtime.try_into().unwrap())
Cast with `as _`.

2023-08-24 13:03 UTC, damb commented on src/trace.rs
> +        self.ptr().samplecnt.try_into().unwrap()
Cast with `as _`.

2023-08-24 13:03 UTC, damb commented on src/trace.rs
> +        self.ptr().numsamples.try_into().unwrap()
Cast with `as _`.

2023-08-24 13:03 UTC, damb commented on src/trace.rs
> +                (buf.len() as c_ulong).into(),
See above. Casting twice is not required.

2023-08-24 13:03 UTC, damb commented on src/trace.rs
> +                (autoheal as c_char).try_into().unwrap(),
See above. Casting twice not required.

2023-08-24 13:03 UTC, damb commented on src/trace.rs
> +                    start_time.try_into().unwrap(),
Cast with `as _`.

2023-08-24 13:03 UTC, damb commented on src/trace.rs
> +                    end_time.try_into().unwrap(),
Cast with `as _`.

2023-08-24 13:03 UTC, damb commented on src/record.rs
> +                (buf.len() as c_ulong).into(),
See above. Casting twice not required.

2023-08-24 13:03 UTC, damb commented on src/pack.rs
> +    let cnt_samples: c_long = 0;
This is dangerous and causes a test failure on my local machine. 

`raw::msr3_pack()` is expecting a pointer to a mutable type for returning the number of packed samples.

```rust
    let mut cnt_samples: c_long = 0;
    let cnt_samples_ptr = (&mut cnt_samples as &mut _) as *mut _;
```

is the way to go.

2023-08-24 16:58 UTC, BIBIN-EUGINE commented on src/pack.rs
> +    let cnt_samples: c_long = 0;
> ```rust
> (&mut cnt_samples as &mut _) as *mut _;
> ```

I am getting a CC error for this conversion, so I recommend to use the below mentioned way
```
    let cnt_samples: c_long = 0;
    let cnt_samples_ptr = (&mut cnt_samples.into()) as *mut _;

```

2023-08-24 19:21 UTC, damb commented on src/pack.rs
> +    let cnt_samples: c_long = 0;
Again, the suggested solution is not correct and results in a test failing on my machine (i.e. `x86_64`). `cnt_samples` must be mutable. The actual problem is that on `arm` `c_long` is defined as `i32` while on `x86` it is `i64`. Does

```rust
let mut cnt_samples: i64 = 0;
let cnt_samples_ptr: *mut i64 = &mut cnt_samples;
```

on your side?

2023-08-24 20:09 UTC, BIBIN-EUGINE commented on src/pack.rs
> +    let cnt_samples: c_long = 0;
> The suggested solution is not correct and results in a test failing on my machine (i.e. `x86_64`). `cnt_samples` must be mutable. The actual problem is that on your architecture `c_long` is defined as `i32` while on my side it is `i64` (see: https://doc.rust-lang.org/std/os/raw/type.c_long.html). Does
> 
> ```rust
> let mut cnt_samples: i64 = 0;
> let cnt_samples_ptr: *mut i64 = &mut cnt_samples;
> ```
> 
> solve the issue on your side?
> 
> EDIT: Thanks for pasting the compiler error 👍.

Thanks @damb it works.

2023-08-24 20:25 UTC, damb commented on src/pack.rs
> +    let cnt_samples: c_long = 0;
Perfect. Thanks.

2023-08-24 20:26 UTC, damb approved these changes

2023-08-24 20:32 UTC, merged

2023-08-24 20:34 UTC, damb commented
Thank you again. It would be nice if you still could check whether the examples need a fix. In case of errors a PR is very welcome.

2023-08-25 01:35 UTC, BIBIN-EUGINE commented
> Thank you again. It would be nice if you still could check whether the examples need a fix. In case of errors a PR is very welcome.

I have  verified all the examples works as expected.

2023-08-25 01:39 UTC, BIBIN-EUGINE commented
> Thanks a lot.
> 
> Could you fix the requested changes, please? Also, could you have a look at the examples in the examples directory since they might require additional changes?
> 
> In addition, do you have experience with ARM based test runners for GitHub actions? It would be nice to have tests being executed on ARM, too.

I haven't explored GitHub actions yet, If you already have experience with this then I am happy for you to pursue.
In addition, I am also seeing some other issues with this crate...will post more about it soon as a separate issue.